### PR TITLE
Remove most LIT Devs references, Fix Nicehash and remove broken links

### PR DESCRIPTION
**Pull request by emilianya**
Hi,

We noticed you resurrected this dead piece of software, which is fine in itself, however you left in alot of references to us which we do not appreciate.
This PR removes most of them, along with broken links, and fixing the nicehash hostnames (which were updated some time ago)

Now lets talk copyright, your discord application, 872392087440621579, uses our assets, in particular "Vukky Miner" without permission. Please refer to the license [here](https://github.com/Vukkyy/vukmoji/blob/master/LICENSE).
Stop using these assets, you do not have permission to do so.

Thanks,
Skelly @ LITDevs

### CODE REVIEW

**Comment by emilianya** [comment]
I also went ahead and bumped pkg to 5.8.0

oh and good luck with people asking you for help, it is incredibly infuriating

**Comment by nyakase** [comment]
I also agree with the comments above.
<small>especially that one about people asking you for support anyway :)</small>

Thanks,
Vukky (LIT Devs Founder)

**Comment by aj-swartz** [comment]
merged. correct me if im wrong but im assuming "Vukky Miner" refers to the lil guy on the side when using rich presence. i'll remove it asap :)

**Comment by Vukkyy** [comment]
you are correct

**Comment by emilianya** [comment]
Hi, looks like the application still uses Vukky Miner
image

**Comment by aj-swartz** [comment]
Hi, unfortunately I don't have control over 872392087440621579. I'm pretty sure it was the original application ID from when SaladBind was still officially supported. I also found this application ID in two other forked repo's. particularly [RuhmitSahu's](https://github.com/RuhmitSahu/SaladBind/blob/5f0b66cdaa714f0bb97abba19712de8366099487/src/presence.js) and [SonGorLick's](https://github.com/SonGorLick/SaladBind/blob/f5008e5a89d05c280d883e48dcf7393897871583/src/presence.js). RadsammyT's repo also contained it initially but [they changed it a while ago](https://github.com/RadsammyT/SaladBind-Archive/commit/bc4dc1828f38a5482d92ca588210714cab7de44e). I went ahead and changed the Discord application ID to one I am able to manage yesterday, though :)

**Comment by emilianya** [comment]
oh wow then its still probably mitch's lol
no worries then

**Pull request merged**
